name: Build

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Compile
      run: go build ./...

    - name: Test
      run: |
        go install github.com/gregoryv/gocolor/cmd/gocolor@latest
        go test -v -coverprofile /tmp/c.out ./... | gocolor
